### ISSUE TITLE
VERIFY: Style active / inactive search result pins

### ISSUE THREAD

**Issue by nvkelso** [tangrams/eraser-map#104]
See related: https://github.com/mapzen/eraser-map/issues/136
- On the style side of things 2 draw rules with appropriate filters looking for `state` property needs to be specified.
  So https://github.com/tangrams/eraser-map/blob/gh-pages/eraser-map.yaml#L891-L898, should look like:

```
    search:
        data: { source: search }
        draw:
            icons:
                size: [36px,46px]
                collide: false
                anchor: top
        active:
            filter: { state: active }
            draw:
                icons:
                    sprite: search-active
        inactive:
            filter: { state: inactive }
            draw:
                icons:
                    sprite: search-inactive
```
