### ISSUE TITLE
Building tilt z-axis effect needs to apply to all building parts

### ISSUE THREAD

**Issue by nvkelso** [tangrams/eraser-map#15]
Currently it's only selecting on building parts, but we need to say if the entire building's area/volume then all of that building's parts should have the tilt applied. /cc @meetar @bcamper

**Comment by nvkelso** [comment]
Related: https://github.com/mapzen/vector-datasource/issues/212

**Comment by meetar** [comment]
Can you describe the situation where you see this, and say more about the way the problem manifests?

**Comment by nvkelso** [comment]
Empire State Building only shows the lower slice of it's building. @sensescape can you include screenshot and more info?

**Comment by meetar** [comment]
Ah, right. Unfortunately we only have access to building parts – we currently have no mechanism to relate parts to each other.

In this case I'd recommend we change the filter to work more like this:

```
if feature.area > 1600 || feature.height > 100 || feature.area * feature.height > 20000
```

If that makes sense to you I'll draw up another set of numbers.

**Comment by sensescape** [comment]
Empire State drawing in parts

<img width="119" alt="screen shot 2015-09-17 at 10 54 02 am" src="https://cloud.githubusercontent.com/assets/466585/9941493/8b50d346-5d2a-11e5-924e-09389b62f85c.png">
<img width="253" alt="screen shot 2015-09-17 at 10 54 11 am" src="https://cloud.githubusercontent.com/assets/466585/9941495/8b6c5b84-5d2a-11e5-9945-1745ce0a02f4.png">
<img width="413" alt="screen shot 2015-09-17 at 10 54 16 am" src="https://cloud.githubusercontent.com/assets/466585/9941494/8b6970cc-5d2a-11e5-9251-7fc5a7702c85.png">

**Comment by bcamper** [comment]
@sensescape can you also attach the scene file?

**Comment by meetar** [comment]
Right. To be clear, these filters would be applied on the server to guide tile generation, and would not be applied in the scene file itself.

**Comment by bcamper** [comment]
Seems either @meetar and I may misunderstand the issue, and/or we're conflating a couple issues at once :)  So taking a look at the scene file will help sort it out!

**Comment by sensescape** [comment]
@bcamper @meetar, it's checked in, eraser-map.yaml

**Comment by meetar** [comment]
Got it! I had initially thought this was a data problem, thanks for the scene file –

So using `area` and `name` filters won't work reliably on buildings, because of our inability to relate building parts to each other – in many cases the building `name` is only set on the building relation, which is often the largest outline. In the case of the Empire State Building, that's the building's base.

Looking at your filters here: https://github.com/tangrams/eraser-map/blob/gh-pages/eraser-map.yaml#L1413-L1416

One solution would be to remove the "name" filters, and add some others which allow buildings over a certain height to always be shown:

```
buildings:
    data: { source: osm }
    filter: 
        any:
            # limit smaller buildings to higher zooms
            - { $zoom: { min: 15 }, height: { min: 200 } }
            - { $zoom: { min: 16 }, height: { min: 100 } }
            - { $zoom: { min: 15 }, area: { min: 5000 } }
            - { $zoom: { min: 16 }, area: { min: 1000 } }
            - { $zoom: { min: 17 }, area: { min: 500 } }
            - { $zoom: { min: 18 } }
```
