### ISSUE TITLE
Bridges have caterpillar caps where they join road network

### ISSUE THREAD

**Issue by nvkelso** [tangrams/eraser-map#155]
From drive test in Phoenix, they have tons of roads and paths going over freeways that show like:
#18/33.38530/-111.94269

![screenshot_2016-02-14-11-22-07](https://cloud.githubusercontent.com/assets/853051/13091665/1eb54e84-d4b1-11e5-9e45-6f9380dd4435.png)

**Comment by nvkelso** [comment]
We need combo of cap styles to fix this:

```
            minor_road_bridge:
                filter: { is_bridge: yes }
                draw:
                    lines:
                        cap: round
                        outline:
                            cap: butt
```
