### ISSUE TITLE
Don't rely on default font size

### ISSUE THREAD

**Issue by bcamper** [tangrams/eraser-map#242]
I've been noticing some odd road labels, and I think that the problem is relying on the default `font.size` parameter. For example, check out these big road labels for 14th Ave, 18th Ave, etc. on Tangram ES:

![native](https://cloud.githubusercontent.com/assets/16733/24617865/2ffb3392-1863-11e7-9384-3bec2fe613d1.PNG)

They look more normal in Tangram JS, but in both cases I think it's falling back on the default font size, which must be smaller in JS (12px) - @tallytalwar or @karimnaaji?

![web](https://cloud.githubusercontent.com/assets/16733/24617869/31386798-1863-11e7-9748-4a5e6fc7159b.png)

This happens on (at least?) a few layers, including secondary and tertiary roads at some zooms. In this example, at z12 we're matching to [`labels-secondary-default`](https://github.com/tangrams/bubble-wrap/blob/gh-pages/bubble-wrap-style.yaml#L2209-L2213), which has no `font` block but inherits some other font params from [`roads`](https://github.com/tangrams/bubble-wrap/blob/gh-pages/bubble-wrap-style.yaml#L1694-L1700).

Starting at z13, the font `size` is explicitly set:

```
                labels-secondary-default:
                    draw:
                        text-blend-order:
                            text_source: global.ux_language_text_source_road_ref_and_name_short
                            visible: global.text_visible_secondary
                labels-secondary-z13:
                    filter:
                        $zoom: [13]
                    draw:
                        text-blend-order:
                            priority: 56
                            visible: global.text_visible_secondary_e
                            #text_source: global.ux_language_text_source_road_ref_and_name_short
                            font:
                                fill: [0.5,0.5,0.5]
                                size: 11px
                                stroke: { color: global.text_stroke, width: 2 }
```

This also begs the question of whether we should even *have* a default `size`, or whether we should be requiring this to be set explicitly for labels to render? cc @matteblair

**Comment by nvkelso** [comment]
I had noticed the same thing using the iOS demo app, thanks for the sleuthing!

From https://mapzen.com/documentation/tangram/draw/#font-parameters:

```
The font object has a number of unique parameters.
None are required, but least one must be specified for a text style to be drawn.
```

I've summarized the defaults below (different than the example in docs):

```
draw:
    text:
        font:
            family: Helvetica
            size: 12px               # with px being the default units
            weight: normal        # is this `400`?
            fill: white                 # arguably this should be black
            #style: italic            # no default (effectively "normal")
            #stroke: { color: white, width: 2 }    # no default
            # transform: uppercase                  # no default
```

My preference is for ES and JS to have the same default text font size (`12px`).
