### ISSUE TITLE
Style route start, stop pins

### ISSUE THREAD

**Issue by nvkelso** [tangrams/eraser-map#64]
During the routing experience, the design shows route-start and route-end pins. Let's add those to the sprite sheet and add scene file styling for them.

**Comment by nvkelso** [comment]
From the duplicate issue:

> https://github.com/tangrams/eraser-map/blob/android/eraser-map.yaml#L764-L787
> 
> Currently a route icon layer is missing all together, I am going to add one as a placeholder in the android branch, for it to be used in eraser-map app code.

**Comment by nvkelso** [comment]
@blair1618 @ecgreb Do we need to do anything (more) in the stylesheet for this one?

I already see in the scene file, and @sensescape has packed those assets into the sprite sheet:

```
    route_icon:
        data: { source: route_icon }
        blend: overlay
        draw:
            icons:
                priority: 1
                sprite: route-start
                size: [38px,49px]
                collide: false
                transition:
                    [show, hide]:
                        time: 0s
```
