### ISSUE TITLE
Directional route location marker

### ISSUE THREAD

**Issue by ecgreb** [tangrams/eraser-map#90]
Right now the route start icon (black pin) is used to show the current position in routing mode. This should instead be a directional arrow icon that can indicate the current position and bearing which moves along the route with the user.

cc @souperneon @sensescape 

https://github.com/tangrams/eraser-map/blob/gh-pages/eraser-map.yaml#L836

![image](https://cloud.githubusercontent.com/assets/464123/11303513/3d174bdc-8f71-11e5-80d8-fd1a3a23d735.png)

**Comment by nvkelso** [comment]
@ecgreb Good catch & debug! 

Related: What are the element names for the route-start and route-stop icons (like `route-icon`, but different)?

**Comment by matteblair** [comment]
Do we want the arrow to lay "flat" on the plane of the ground when the view tilts?

**Comment by ecgreb** [comment]
@nvkelso Route start and stop have not been added to the stylesheet (or app) yet but I would imagine something like this would do the trick:

```
    route_start:
        data: { source: route_start }
        draw:
            icons:
                priority: 1
                sprite: route-start
                size: [38px,49px]
                collide: false
                transition:
                    [show, hide]:
                        time: 0s
    route_stop:
        data: { source: route_stop }
        draw:
            icons:
                priority: 1
                sprite: route-stop
                size: [38px,49px]
                collide: false
                transition:
                    [show, hide]:
                        time: 0s
```
